# ROS2 parameter file format
mpu6050_node:
  ros__parameters:
    # I2C Bus URI used to communicate with I2C devices
    bus_uri: "/dev/i2c-1"

    # I2C address of MPU6050
    mpu_address: 0x68

    # Frequency in Hertz which IMU data is published
    pub_rate: 25

    # Frame id of IMU message
    frame_id: "imu"

    # Offsets to fix wrong values caused by misalignment
    # Sequence is (ax, ay, az, gx, gy, gz)
    axes_offsets: [-2589, -1383, 1628, -20, -34, 53]

    # PID constants used in calibration procedure
    ki: 0.2
    kp: 0.1

    # The calibration process is finished when the error is approximate zero with
    # the precision set by delta
    delta: 0.5
